export const INCHARGE_COMPLAINTS = [
  {
    id: "CMP-1042",
    labName: "DBMS Lab - Block B",
    issueType: "Hardware",
    resourceId: "PC-014",
    description: "Monitor flickers intermittently and turns black after 10 minutes.",
    reportedBy: "Aarav Mehta (21CS1042)",
    status: "In Progress",
    createdAt: "2026-07-05T10:00:00.000Z",
  },
  {
    id: "CMP-1039",
    labName: "OS Lab - Block B",
    issueType: "Software",
    resourceId: "PC-007",
    description: "Wireshark crashes on launch, packet capture not starting.",
    reportedBy: "Ishita Rao (21CS1017)",
    status: "Resolved",
    createdAt: "2026-06-28T09:30:00.000Z",
  },
  {
    id: "CMP-1051",
    labName: "OS Lab - Block B",
    issueType: "Hardware",
    resourceId: "PC-021",
    description: "Keyboard has three unresponsive keys (A, S, D).",
    reportedBy: "Rohan Patel (21CS1029)",
    status: "Pending",
    createdAt: "2026-07-09T14:12:00.000Z",
  },
  {
    id: "CMP-1055",
    labName: "DBMS Lab - Block B",
    issueType: "Software",
    resourceId: "PC-003",
    description: "MySQL Workbench fails to connect to local server instance.",
    reportedBy: "Devansh Shah (21CS1005)",
    status: "Pending",
    createdAt: "2026-07-12T11:45:00.000Z",
  },
];

export const RESOURCE_REQUESTS = [
  {
    id: "REQ-2081",
    resourceId: "PROJ-002",
    resourceName: "Epson Projector",
    labName: "DBMS Lab - Block B",
    requestedBy: "Meera Iyer (21CS1051)",
    purpose: "Group project demo for DBMS mini-project evaluation.",
    requestedFor: "18 Jul 2026, 2:00 PM – 4:00 PM",
    status: "Pending",
    createdAt: "2026-07-15T08:20:00.000Z",
  },
  {
    id: "REQ-2076",
    resourceId: "RPI-004",
    resourceName: "Raspberry Pi 4 Kit",
    labName: "OS Lab - Block B",
    requestedBy: "Kabir Malhotra (21CS1033)",
    purpose: "OS scheduling assignment prototype.",
    requestedFor: "12 Jul 2026 – 19 Jul 2026",
    status: "Approved",
    createdAt: "2026-07-10T12:00:00.000Z",
  },
  {
    id: "REQ-2069",
    resourceId: "PC-019",
    resourceName: "Lab PC - Extended Access",
    labName: "DBMS Lab - Block B",
    requestedBy: "Sanya Kapoor (21CS1061)",
    purpose: "Extended lab access for hackathon practice.",
    requestedFor: "08 Jul 2026, 6:00 PM – 9:00 PM",
    status: "Rejected",
    createdAt: "2026-07-06T09:00:00.000Z",
  },
];

export const LAB_RESOURCES = [
  { id: "PC-001", name: "Lab PC (i5, 16GB)", labName: "DBMS Lab - Block B", category: "Hardware", status: "Available" },
  { id: "PC-003", name: "Lab PC (i5, 16GB)", labName: "DBMS Lab - Block B", category: "Hardware", status: "Under Maintenance" },
  { id: "PC-014", name: "Lab PC (i5, 16GB)", labName: "DBMS Lab - Block B", category: "Hardware", status: "Under Maintenance" },
  { id: "PROJ-002", name: "Epson Projector", labName: "DBMS Lab - Block B", category: "Hardware", status: "Borrowed" },
  { id: "PC-007", name: "Lab PC (i7, 16GB)", labName: "OS Lab - Block B", category: "Hardware", status: "Available" },
  { id: "PC-019", name: "Lab PC (i7, 16GB)", labName: "OS Lab - Block B", category: "Hardware", status: "Available" },
  { id: "PC-021", name: "Lab PC (i7, 16GB)", labName: "OS Lab - Block B", category: "Hardware", status: "Under Maintenance" },
  { id: "RPI-004", name: "Raspberry Pi 4 Kit", labName: "OS Lab - Block B", category: "Hardware", status: "Borrowed" },
];

export const MAINTENANCE_LOG = [
  {
    id: "MNT-301",
    resourceId: "PC-014",
    labName: "DBMS Lab - Block B",
    issue: "Monitor flicker — replacement display cable requested.",
    loggedOn: "06 Jul 2026",
    status: "In Progress",
  },
  {
    id: "MNT-298",
    resourceId: "PC-021",
    labName: "OS Lab - Block B",
    issue: "Three keys unresponsive — keyboard swap scheduled.",
    loggedOn: "10 Jul 2026",
    status: "Pending",
  },
  {
    id: "MNT-290",
    resourceId: "PC-003",
    labName: "DBMS Lab - Block B",
    issue: "Motherboard reseat after repeated shutdowns.",
    loggedOn: "01 Jul 2026",
    status: "Pending",
  },
  {
    id: "MNT-276",
    resourceId: "PC-011",
    labName: "DBMS Lab - Block B",
    issue: "RAM upgrade completed, unit verified and returned to service.",
    loggedOn: "22 Jun 2026",
    status: "Resolved",
  },
];