export const LABS = [
  "DS Lab - Block A",
  "DBMS Lab - Block B",
  "Networks Lab - Block A",
  "OS Lab - Block B",
  "WebTech Lab - Block C",
  "Micro Lab - Block C",
];

export const ALL_COMPLAINTS = [
  {
    id: "CMP-1042",
    labName: "DBMS Lab - Block B",
    issueType: "Hardware",
    resourceId: "PC-014",
    description: "Monitor flickers intermittently and turns black after 10 minutes.",
    reportedBy: "Aarav Mehta (21CS1042)",
    status: "In Progress",
    createdAt: "2026-07-05T10:00:00.000Z",
  },
  {
    id: "CMP-1039",
    labName: "Networks Lab - Block A",
    issueType: "Software",
    resourceId: "PC-007",
    description: "Wireshark crashes on launch, packet capture not starting.",
    reportedBy: "Ishita Rao (21CS1017)",
    status: "Resolved",
    createdAt: "2026-06-28T09:30:00.000Z",
  },
  {
    id: "CMP-1051",
    labName: "OS Lab - Block B",
    issueType: "Hardware",
    resourceId: "PC-021",
    description: "Keyboard has three unresponsive keys (A, S, D).",
    reportedBy: "Rohan Patel (21CS1029)",
    status: "Pending",
    createdAt: "2026-07-09T14:12:00.000Z",
  },
  {
    id: "CMP-1055",
    labName: "DS Lab - Block A",
    issueType: "Software",
    resourceId: "PC-003",
    description: "Code::Blocks fails to compile, missing MinGW path.",
    reportedBy: "Devansh Shah (21CS1005)",
    status: "Pending",
    createdAt: "2026-07-12T11:45:00.000Z",
  },
  {
    id: "CMP-1058",
    labName: "WebTech Lab - Block C",
    issueType: "Hardware",
    resourceId: "PC-032",
    description: "Ethernet port not detecting cable, no network access.",
    reportedBy: "Meera Iyer (21CS1051)",
    status: "Pending",
    createdAt: "2026-07-14T16:05:00.000Z",
  },
  {
    id: "CMP-1060",
    labName: "Micro Lab - Block C",
    issueType: "Hardware",
    resourceId: "KIT-8085-02",
    description: "8085 trainer kit display not powering on.",
    reportedBy: "Kabir Malhotra (21CS1033)",
    status: "In Progress",
    createdAt: "2026-07-16T09:15:00.000Z",
  },
];

export const ALL_RESOURCES = [
  { id: "PC-001", name: "Lab PC (i5, 16GB)", labName: "DS Lab - Block A", category: "Hardware", status: "Available" },
  { id: "PC-003", name: "Lab PC (i5, 16GB)", labName: "DS Lab - Block A", category: "Hardware", status: "Under Maintenance" },
  { id: "PC-007", name: "Lab PC (i7, 16GB)", labName: "Networks Lab - Block A", category: "Hardware", status: "Available" },
  { id: "PC-014", name: "Lab PC (i5, 16GB)", labName: "DBMS Lab - Block B", category: "Hardware", status: "Under Maintenance" },
  { id: "PC-019", name: "Lab PC (i7, 16GB)", labName: "OS Lab - Block B", category: "Hardware", status: "Available" },
  { id: "PC-021", name: "Lab PC (i7, 16GB)", labName: "OS Lab - Block B", category: "Hardware", status: "Under Maintenance" },
  { id: "PC-032", name: "Lab PC (i5, 8GB)", labName: "WebTech Lab - Block C", category: "Hardware", status: "Under Maintenance" },
  { id: "PROJ-002", name: "Epson Projector", labName: "DBMS Lab - Block B", category: "Hardware", status: "Borrowed" },
  { id: "RPI-004", name: "Raspberry Pi 4 Kit", labName: "OS Lab - Block B", category: "Hardware", status: "Borrowed" },
  { id: "KIT-8085-02", name: "8085 Microprocessor Trainer Kit", labName: "Micro Lab - Block C", category: "Hardware", status: "Under Maintenance" },
  { id: "SW-MYSQL", name: "MySQL Workbench License", labName: "DBMS Lab - Block B", category: "Software", status: "Available" },
];

export const APPROVAL_REQUESTS = [
  {
    id: "REQ-2081",
    resourceId: "PROJ-002",
    resourceName: "Epson Projector",
    labName: "DBMS Lab - Block B",
    requestedBy: "Meera Iyer (21CS1051)",
    purpose: "Group project demo for DBMS mini-project evaluation.",
    requestedFor: "18 Jul 2026, 2:00 PM – 4:00 PM",
    status: "Pending",
    createdAt: "2026-07-15T08:20:00.000Z",
  },
  {
    id: "REQ-2076",
    resourceId: "RPI-004",
    resourceName: "Raspberry Pi 4 Kit",
    labName: "OS Lab - Block B",
    requestedBy: "Kabir Malhotra (21CS1033)",
    purpose: "OS scheduling assignment prototype.",
    requestedFor: "12 Jul 2026 – 19 Jul 2026",
    status: "Approved",
    createdAt: "2026-07-10T12:00:00.000Z",
  },
  {
    id: "REQ-2088",
    resourceId: "KIT-8085-02",
    resourceName: "8085 Microprocessor Trainer Kit",
    labName: "Micro Lab - Block C",
    requestedBy: "Sanya Kapoor (21CS1061)",
    purpose: "Extra practice for upcoming microprocessor viva.",
    requestedFor: "20 Jul 2026, 3:00 PM – 5:00 PM",
    status: "Pending",
    createdAt: "2026-07-17T10:00:00.000Z",
  },
];

export const LAB_MANUALS = [
  { id: "LM001", subject: "Data Structures Lab", title: "Data Structures Lab Manual", fileType: "PDF", updated: "12 Jun 2026", semester: "3" },
  { id: "LM002", subject: "Database Management Lab", title: "SQL Practicals & Schema Guide", fileType: "PDF", updated: "03 Jun 2026", semester: "5" },
  { id: "LM003", subject: "Computer Networks Lab", title: "Networking Protocols Manual", fileType: "PDF", updated: "28 May 2026", semester: "5" },
  { id: "LM004", subject: "Operating Systems Lab", title: "Process Scheduling Exercises", fileType: "DOCX", updated: "20 May 2026", semester: "5" },
  { id: "LM005", subject: "Web Technologies Lab", title: "Frontend & Backend Lab Guide", fileType: "PDF", updated: "15 Jun 2026", semester: "5" },
  { id: "LM006", subject: "Microprocessors Lab", title: "8085 Assembly Programs", fileType: "PDF", updated: "09 Jun 2026", semester: "4" },
];

export const MAINTENANCE_LOG = [
  { id: "MNT-301", resourceId: "PC-014", labName: "DBMS Lab - Block B", issue: "Monitor flicker — replacement display cable requested.", loggedOn: "06 Jul 2026", status: "In Progress" },
  { id: "MNT-298", resourceId: "PC-021", labName: "OS Lab - Block B", issue: "Three keys unresponsive — keyboard swap scheduled.", loggedOn: "10 Jul 2026", status: "Pending" },
  { id: "MNT-295", resourceId: "PC-032", labName: "WebTech Lab - Block C", issue: "Ethernet port faulty, NIC replacement in progress.", loggedOn: "14 Jul 2026", status: "In Progress" },
  { id: "MNT-290", resourceId: "PC-003", labName: "DS Lab - Block A", issue: "Motherboard reseat after repeated shutdowns.", loggedOn: "01 Jul 2026", status: "Pending" },
  { id: "MNT-284", resourceId: "KIT-8085-02", labName: "Micro Lab - Block C", issue: "Trainer kit power supply unit inspection.", loggedOn: "16 Jul 2026", status: "Pending" },
  { id: "MNT-276", resourceId: "PC-011", labName: "DBMS Lab - Block B", issue: "RAM upgrade completed, unit verified and returned to service.", loggedOn: "22 Jun 2026", status: "Resolved" },
];